format_macro_matchers = true
format_macro_bodies= true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
unstable_features = true
version = "Two"
wrap_comments = true
